use async_trait::async_trait;
use qa_catalog_sdk::TestBundle;
use sea_orm::sea_query::Expr;
use sea_orm::{ActiveValue, ColumnTrait, EntityTrait, FromQueryResult, Order, QueryFilter, QueryOrder, QuerySelect};
use time::OffsetDateTime;
use toolkit_db::secure::{DBRunner, SecureDeleteExt, SecureEntityExt, secure_insert};
use toolkit_security::AccessScope;
use uuid::Uuid;

use crate::domain::error::DomainError;
use crate::domain::repos::BundlesRepository;
use crate::infra::storage::db::db_err;
use crate::infra::storage::entity::test_bundle::{
    ActiveModel as BundleAM, Column as BundleColumn, Entity as BundleEntity,
};
use crate::infra::storage::mapper::{bundle_to_sdk, db_i64_from_u64};

/// ORM-based implementation of the `BundlesRepository` trait.
#[derive(Clone, Default)]
pub struct OrmBundlesRepository;

#[async_trait]
impl BundlesRepository for OrmBundlesRepository {
    async fn create<C: DBRunner>(
        &self,
        runner: &C,
        scope: &AccessScope,
        tenant_id: Uuid,
        bundle: TestBundle,
    ) -> Result<TestBundle, DomainError> {
        let bundle_id = bundle.id;
        let am = BundleAM {
            id: ActiveValue::Set(bundle.id),
            tenant_id: ActiveValue::Set(tenant_id),
            storage_ref: ActiveValue::Set(bundle.storage_ref),
            checksum_sha256: ActiveValue::Set(bundle.checksum_sha256),
            size_bytes: ActiveValue::Set(db_i64_from_u64(bundle.size_bytes, "size_bytes")?),
            expires_at: ActiveValue::Set(bundle.expires_at),
            created_at: ActiveValue::Set(bundle.created_at),
        };

        match secure_insert::<BundleEntity>(am, scope, runner).await {
            Ok(model) => bundle_to_sdk(model),
            // Bundle IDs are freshly generated by the service before the blob
            // is written, so a duplicate is an internal invariant violation
            // (an ID was reused), not a user-visible conflict — but it must
            // still not read as an opaque `Database` error.
            Err(e) if e.is_unique_violation() => Err(DomainError::Internal(format!(
                "bundle id {bundle_id} already exists"
            ))),
            Err(e) => Err(db_err(e)),
        }
    }

    async fn get<C: DBRunner>(
        &self,
        runner: &C,
        scope: &AccessScope,
        id: Uuid,
    ) -> Result<Option<TestBundle>, DomainError> {
        let found = BundleEntity::find()
            .filter(sea_orm::Condition::all().add(BundleColumn::Id.eq(id)))
            .secure()
            .scope_with(scope)
            .one(runner)
            .await
            .map_err(db_err)?;

        found.map(bundle_to_sdk).transpose()
    }

    async fn delete_expired<C: DBRunner>(
        &self,
        runner: &C,
        scope: &AccessScope,
        now: OffsetDateTime,
    ) -> Result<Vec<TestBundle>, DomainError> {
        let rows = BundleEntity::find()
            .filter(sea_orm::Condition::all().add(BundleColumn::ExpiresAt.lte(now)))
            .secure()
            .scope_with(scope)
            .all(runner)
            .await
            .map_err(db_err)?;

        if rows.is_empty() {
            return Ok(Vec::new());
        }

        // Delete exactly the rows just read (by ID) rather than re-evaluating
        // the expiry predicate, so the returned descriptors always match what
        // was removed and the caller never GCs a blob whose row survived.
        let ids: Vec<Uuid> = rows.iter().map(|m| m.id).collect();
        BundleEntity::delete_many()
            .filter(sea_orm::Condition::all().add(BundleColumn::Id.is_in(ids)))
            .secure()
            .scope_with(scope)
            .exec(runner)
            .await
            .map_err(db_err)?;

        rows.into_iter().map(bundle_to_sdk).collect()
    }

    async fn tenants_with_expired_bundles<C: DBRunner>(
        &self,
        runner: &C,
        scope: &AccessScope,
        now: OffsetDateTime,
    ) -> Result<Vec<Uuid>, DomainError> {
        let rows: Vec<TenantIdRow> = BundleEntity::find()
            .secure()
            .scope_with(scope)
            .project_all(runner, |query| {
                query
                    .filter(
                        sea_orm::Condition::all().add(BundleColumn::ExpiresAt.lte(now)),
                    )
                    .select_only()
                    .column(BundleColumn::TenantId)
                    .distinct()
                    .order_by(Expr::col(BundleColumn::TenantId), Order::Asc)
                    .into_model::<TenantIdRow>()
            })
            .await
            .map_err(db_err)?;

        Ok(rows.into_iter().map(|row| row.tenant_id).collect())
    }
}

/// The one-column projection [`OrmBundlesRepository::tenants_with_expired_bundles`]
/// reads.
#[derive(Debug, FromQueryResult)]
struct TenantIdRow {
    tenant_id: Uuid,
}
